In [1]:
import numpy as np

In [3]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [4]:
print(a)

[1 2 3]


In [5]:
type(a)

numpy.ndarray

In [6]:
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [7]:
c = np.array([1,2,3,4,5], ndmin = 2)
print(c)

[[1 2 3 4 5]]


In [8]:
c = np.array([1,2,3,4,5], ndmin = 3)
print(c)

[[[1 2 3 4 5]]]


In [9]:
c = np.array([1,2,3,4,5], ndmin = 1)
print(c)

[1 2 3 4 5]


In [10]:
x = [1,2,3]
a = np.asarray(x)
a

array([1, 2, 3])

In [11]:
print(a)

[1 2 3]


In [12]:
import numpy as np
student = np.dtype([('name','S20'), ('age', 'i1'), ('marks', 'f4')]) 
a = np.array([('abc', 21, 50),('xyz', 18, 75)], dtype = student) 
print(a)

[(b'abc', 21, 50.) (b'xyz', 18, 75.)]


In [13]:
s = b'Hello World'
a = np.frombuffer(s, dtype = 'S1')
print(a)

[b'H' b'e' b'l' b'l' b'o' b' ' b'W' b'o' b'r' b'l' b'd']


In [14]:
list = range(5)
list

range(0, 5)

In [15]:
print(list)

range(0, 5)


In [16]:
type(list)

range

In [17]:
x = np.fromiter(list,dtype = float)
print(x)

[0. 1. 2. 3. 4.]


In [18]:
a = np.array([[1,2,3],[3,4,5],[4,5,6]])
print(a)

[[1 2 3]
 [3 4 5]
 [4 5 6]]


In [19]:
print(a[...,2])

[3 5 6]


In [20]:
type(a[...,2])

numpy.ndarray

In [21]:
a = np.array([[1,2,3],[3,4,5],[4,5,6]])
print(a[...,0])
print(a[...,1])
print(a[...,2])
print(a[0,...])
print(a[1,...])
print(a[2,...])

[1 3 4]
[2 4 5]
[3 5 6]
[1 2 3]
[3 4 5]
[4 5 6]


In [22]:
x = np.array([[  0,  1,  2],[  3,  4,  5],[  6,  7,  8],[  9,  10,  11]])  
rows = [[0,1],[3,2]]
cols = [[1,2],[0,2]]
print(x[rows,cols])

[[1 5]
 [9 8]]


In [23]:
rows = [[0,1,3,2]]
cols = [[1,2,0,2]]
print(x[rows,cols])

[[1 5 9 8]]


In [24]:
a = np.array([np.nan, 1,2,np.nan, 3,4,5])
print(a[~np.isnan(a)])
print(a[np.isnan(a)])

[1. 2. 3. 4. 5.]
[nan nan]


In [25]:
b = np.array([1,2+6j,5,3.5+5j])
print(b[np.iscomplex(b)])
print(b[~np.iscomplex(b)])

[2. +6.j 3.5+5.j]
[1.+0.j 5.+0.j]


In [26]:
x = np.arange(32).reshape(8,4)
print(x)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]


In [27]:
x = np.arange(32).reshape((8,4))
print(x)
print(x[[4,2,1,7]])
print(x[[4,2,1,7],[0,1,2,3]])
print(x[...,1])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]
[[16 17 18 19]
 [ 8  9 10 11]
 [ 4  5  6  7]
 [28 29 30 31]]
[16  9  6 31]
[ 1  5  9 13 17 21 25 29]


In [28]:
print(x[[1,5,7,2],[0,3,1,2]])
print(x[np.ix_([1,5,7,2],[0,3,1,2])])

[ 4 23 29 10]
[[ 4  7  5  6]
 [20 23 21 22]
 [28 31 29 30]
 [ 8 11  9 10]]


In [29]:
a = np.array([[ 0, 0, 0],
           [10,10,10],
           [20,20,20],
           [30,30,30]])
b = np.array([[1],[2],[3],[4]])
print(a * b)

[[  0   0   0]
 [ 20  20  20]
 [ 60  60  60]
 [120 120 120]]


In [30]:
a = np.array([[ 0, 0, 0],
           [10,10,10],
           [20,20,20],
           [30,30,30]])
b = np.array([[1],[2],[3],[4]])
print(a * b)

[[  0   0   0]
 [ 20  20  20]
 [ 60  60  60]
 [120 120 120]]


In [31]:
a = np.array([[ 0, 0, 0],
           [10,10,10],
           [20,20,20],
           [30,30,30]])
b = np.array([1,2,3])
print(a * b)

[[ 0  0  0]
 [10 20 30]
 [20 40 60]
 [30 60 90]]


In [32]:
a = np.arange(6).reshape(2,3)
for x in np.nditer(a.T):
    print (x, end=", " )
print ('\n')
 
for x in np.nditer(a.T,order='C'):
    print (x, end=", " )
print ('\n')

0, 1, 2, 3, 4, 5, 

0, 3, 1, 4, 2, 5, 



In [33]:
a = np.arange(8).reshape(2,2,2)
print(a)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [34]:
print(a[0,0,0])
print(a[0,0,1])
print(a[0,1,0])
print(a[0,1,1])

0
1
2
3


In [35]:
print(a[1,0,0])
print(a[1,0,1])
print(a[1,1,0])
print(a[1,1,1])

4
5
6
7


In [36]:
x = np.array([4,5,6])
y = np.array([[1],[2],[3]])
b = np.broadcast(x,y)
print(b)

# python
## python
python
* python
+ python
- python
**python** 
***python*** 
__python__ 
___python___
python | R | MATLAB |
--------------|--------|------|
接口统一，学习曲线平缓 | 接口众多，学习曲线陡峭 | 自由度大，学习曲线较为平缓 |
开源免费 | 开源免费 | 商业收费 |

In [38]:
x = np.array(([1,2],[3,4]))
y = np.expand_dims(x,axis=2)
print(x)
print(y)

[[1 2]
 [3 4]]
[[[1]
  [2]]

 [[3]
  [4]]]


In [40]:
x = np.arange(9).reshape(1,3,3)
y = np.squeeze(x)
print(x)
print(y)

[[[0 1 2]
  [3 4 5]
  [6 7 8]]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [41]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
print(np.concatenate((a,b),axis= 0))
print(np.concatenate((a,b),axis= 1))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


In [43]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
print(np.stack((a,b),0))
print(np.stack((a,b),1))
print(np.stack((a,b),2))

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
[[[1 2]
  [5 6]]

 [[3 4]
  [7 8]]]
[[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]


In [48]:
a = np.arange(16).reshape(4,4)
b = np.hsplit(a,2)
print(b)
c = np.vsplit(a,2)
print(c)

[array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])]
[array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])]


In [44]:
a = np.arange(9)
b = np.split(a,[4,7])
print(b)

[array([0, 1, 2, 3]), array([4, 5, 6]), array([7, 8])]


In [46]:
a = np.array([[1,2,3],[4,5,6]])
b = np.resize(a,(3,3))
print(b)

[[1 2 3]
 [4 5 6]
 [1 2 3]]


In [49]:
a = np.array([[1,2],[3,4],[5,6]])
print(np.insert(a,3,[11,12]))
print(np.insert(a,1,[11],axis=0))
print(np.insert(a,1,[11],axis=1))

[ 1  2  3 11 12  4  5  6]
[[ 1  2]
 [11 11]
 [ 3  4]
 [ 5  6]]
[[ 1 11  2]
 [ 3 11  4]
 [ 5 11  6]]


In [50]:
a = np.array([5,2,6,2,7,5,6,8,2,9])
 
print ('第一个数组：')
print (a)
print ('\n')
 
print ('第一个数组的去重值：')
u = np.unique(a)
print (u)
print ('\n')
 
print ('去重数组的索引数组：')
u,indices = np.unique(a, return_index = True)
print (indices)
print ('\n')
 
print ('我们可以看到每个和原数组下标对应的数值：')
print (a)
print ('\n')
 
print ('去重数组的下标：')
u,indices = np.unique(a,return_inverse = True)
print (u)
print ('\n')
 
print ('下标为：')
print (indices)
print ('\n')
 
print ('使用下标重构原数组：')
print (u[indices])
print ('\n')
 
print ('返回去重元素的重复数量：')
u,indices = np.unique(a,return_counts = True)
print (u)
print (indices)

第一个数组：
[5 2 6 2 7 5 6 8 2 9]


第一个数组的去重值：
[2 5 6 7 8 9]


去重数组的索引数组：
[1 0 2 4 7 9]


我们可以看到每个和原数组下标对应的数值：
[5 2 6 2 7 5 6 8 2 9]


去重数组的下标：
[2 5 6 7 8 9]


下标为：
[1 0 2 0 3 1 2 4 0 5]


使用下标重构原数组：
[5 2 6 2 7 5 6 8 2 9]


返回去重元素的重复数量：
[2 5 6 7 8 9]
[3 2 2 1 1 1]


In [2]:
a = np.char.join(':','runoob')
print (a)
print(type(a))

r:u:n:o:o:b
<class 'numpy.ndarray'>


In [3]:
a = np.array([[10,7,4],[3,2,1]])
print(np.percentile(a,50,axis=0,keepdims=True))

[[6.5 4.5 2.5]]


In [5]:
a = np.array([[3,7],[9,1]])
print(np.sort(a))

[[3 7]
 [1 9]]


In [11]:
a = np.array([5,8,9,7])
print(np.partition(a,(0,3)))

[5 7 8 9]


In [14]:
arr = np.array([46, 57, 23, 39, 1, 10, 0, 120])
arr[np.argpartition(arr, 2)[-2]]

46

In [16]:
x = np.arange(9).reshape(3,3)
condition = np.mod(x,2) == 0
print(condition)
print(np.extract(x,condition))
print(np.extract(condition,x))

[[ True False  True]
 [False  True False]
 [ True False  True]]
[False  True False  True False  True False  True]
[0 2 4 6 8]


In [21]:
a = np.arange(6).reshape(2,3)
print(id(a))
b = a.view()
b.shape = 3,2
print(id(b))
print(b)
print(a)

1848919987104
1848919987504
[[0 1]
 [2 3]
 [4 5]]
[[0 1 2]
 [3 4 5]]


In [22]:
a = np.arange(6).reshape(2,3)
print(id(a))
b = a.view()
b[0,0] = 100
print(id(b))
print(b)
print(a)


1848919987904
1848919987104
[[100   1   2]
 [  3   4   5]]
[[100   1   2]
 [  3   4   5]]
